title: Hugh's Sharing Notes
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://HughKu.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author:
  name: Hugh Ku
  email: hughku@gmail.com
  github_username:  HughKu
  linkedin_username: wei-lin-ku-4552a956
author: Wei-Lin (Hugh) Ku # add your name
author-img: hugh-ku.jpg # add your photo
about-author: 'I enjoy applying machine learning and deep learning to data of different fields from image and video to finance. Mostly speak Python and understand C++ and Javascript.' # add description
social-github: HughKu # add your Github handle
social-linkedin: wei-lin-ku-4552a956 # add your Linkedin handle
social-email: hughku@gmail.com # add your Email address

# Disqus
discus-identifier: 'hughku' # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
